export const surpriseMePrompts = [
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A traveler standing on the top of a mountain admiring the landscape around him.",
  "A passenger looking out the window of a train sees the cities and villages he passes by.",
  "An adventurer sitting next to a lighthouse notices a ship appearing in the distance.",
  "An explorer camping in a desert counts the stars in the night sky.",
  "A nature lover walking in a forest makes friends with the animals he encounters.",
  " Colorful flowers coming out of the tip of a pen",
  " A bedroom where a cat and a dog sleep together",
  " A pirate ship standing by a lighthouse",
  "An oven where cheese melts on a pizza slice",
  "A picnic area where a kite flies in the sky",
];
